INSERT INTO CURRENCY_EXCHANGE_RATE (id, exchange_from, exchange_to, EXCHANGE_RATE, PORT) VALUES(1001, 'USD','EUR',0.94,0);

INSERT INTO CURRENCY_EXCHANGE_RATE (id, exchange_from, exchange_to, EXCHANGE_RATE, PORT) VALUES(1002, 'EUR','USD',1.06,0);

INSERT INTO CURRENCY_EXCHANGE_RATE (id, exchange_from, exchange_to, EXCHANGE_RATE, PORT) VALUES(1003, 'USD','MXN',17.95,0);

INSERT INTO CURRENCY_EXCHANGE_RATE (id, exchange_from, exchange_to, EXCHANGE_RATE, PORT) VALUES(1004, 'MXN','USD',0.05,0);
